#ifndef SYMBOL_TABLE_H
#define SYMBOL_TABLE_H

// Include necessary libraries
#include <stdlib.h>

// Use a prime number for the hash table size to reduce collisions
#define HASH_TABLE_SIZE 101  // Prime number size for better distribution

// Symbol structure representing each entry in the symbol table linked list
typedef struct Symbol {
    char *name;              // The name of the symbol
    char *type;              // The type of the symbol (e.g., int, float, etc.)
    int index;               // The index generated by the hash function
    struct Symbol *next;     // Pointer to the next symbol in the list (linked list)
} Symbol;

// SymbolTable structure to store the hash table (array of symbol pointers)
typedef struct SymbolTable {
    Symbol *table[HASH_TABLE_SIZE];  // Hash table of symbols
} SymbolTable;

// Function Declerations
unsigned int hashFunction(const char *name);
void initSymbolTable(SymbolTable *symbolTable);
Symbol* createSymbol(const char *name, const char *type, int index);
void insertSymbol(SymbolTable *symbolTable, const char *name, const char *type);
Symbol* findSymbol(SymbolTable *symbolTable, const char *name);
void freeSymbolTable(SymbolTable *symbolTable);

#endif // SYMBOL_TABLE_H
